site_name: Liquality
site_description: Liquality documentation
site_author: Gr0kchain
site_url: https://liquality.io
repo_name: liquality/docs
repo_url: https://github.com/liquality/
copyright: Copyright &copy; 2018 - 2020 Liquality
nav:
  - Welcome : index.md
  - Getting Started : getting_started.md
  - Tutorials : getting_started.md
  - Examples : examples.md
  - Value Management System :
    - Introduction : server/administration/introduction.md
    - Architecture : server/administration/architecture.md
    - Installation :
      - Prerequisites : server/administration/prerequisites.md
      - Server : server/administration/installing_agent.md
      - Client : server/administration/installing_interface.md
    - User Guide : 
      - Performing a swap : server/user/index.md
  - Web Extension :
    - Introduction : web_extension/introduction.md
  - Wallet SDK :
    - Index : sdk/index.md
    - Reference : https://liquality.github.io/chainabstractionlayer/
theme:
    name: material
    logo: ../assets/logo.png
    language: en  
    include_homepage_in_sidebar: false
    collapse_navigation: false
    features:
        - tabs
    palette:
        primary: #9339fc
        accent: #9339fc
    font:
        text: Roboto
        code: Roboto Mono
extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/liquality
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/liquality_io
    - icon: fontawesome/brands/telegram
      link: https://t.me/liquality
    - icon: fontawesome/brands/medium
      link: https://medium.com/liquality

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: true
  - toc:
      permalink: true